/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/role-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles */
        get: operations["roles_api_v1_catalog_role_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employees */
        get: operations["employees_api_v1_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee */
        get: operations["employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/development": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Development */
        get: operations["development_api_v1_employees__employee_id__development_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_employees__employee_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/activities/{event_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completion */
        post: operations["completion_api_v1_employees__employee_id__activities__event_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/career-goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Goal */
        patch: operations["goal_api_v1_employees__employee_id__career_goal_patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/activities/{event_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin */
        post: operations["begin_api_v1_employees__employee_id__activities__event_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/participations/{record_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Participation */
        post: operations["cancel_participation_api_v1_employees__employee_id__participations__record_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last Recommendation */
        get: operations["last_recommendation_api_v1_employees__employee_id__recommendations_get"];
        put?: never;
        /** Generate Recommendation */
        post: operations["generate_recommendation_api_v1_employees__employee_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hr/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hr Overview */
        get: operations["hr_overview_api_v1_hr_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hr/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_hr_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hr/import/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_api_v1_hr_import_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOption */
        ActivityOption: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Format */
            format: string;
            /** Duration Hours */
            duration_hours: number;
            /** Next Session */
            next_session: string | null;
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "continue";
            /** Gains */
            gains: components["schemas"]["SkillGain"][];
            /** Can Complete */
            can_complete: boolean;
            /** Record Id */
            record_id: string | null;
            /** Preparatory For */
            preparatory_for?: string[];
            /** Sessions */
            sessions?: string[];
            /** Participation Status */
            participation_status?: string | null;
            /**
             * Can Cancel
             * @default false
             */
            can_cancel: boolean;
            /**
             * Expected Progress
             * @default 0
             */
            expected_progress: number;
        };
        /** Body_upload_api_v1_hr_import_post */
        Body_upload_api_v1_hr_import_post: {
            /** Employees */
            employees?: string | null;
            /** History */
            history?: string | null;
        };
        /** CareerGoal */
        CareerGoal: {
            /** Target Role */
            target_role: string;
            /**
             * Target Grade
             * @enum {string}
             */
            target_grade: "Junior" | "Middle" | "Senior" | "Lead";
        };
        /** CompletionInput */
        CompletionInput: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Record Id */
            record_id?: string | null;
            /** Session Date */
            session_date?: string | null;
        };
        /** CompletionResult */
        CompletionResult: {
            /** Record Id */
            record_id: string;
            /** Gains */
            gains: components["schemas"]["SkillGain"][];
            /** Before Progress */
            before_progress: number;
            development: components["schemas"]["Development"];
        };
        /** Development */
        Development: {
            /** Employee Id */
            employee_id: string;
            /** As Of Date */
            as_of_date: string;
            /** Revision */
            revision: number;
            /**
             * Context Version
             * @default
             */
            context_version: string;
            goal: components["schemas"]["Goal"];
            /** Progress */
            progress: number;
            /** Skills */
            skills: components["schemas"]["SkillState"][];
            /** Critical Gaps */
            critical_gaps: number;
            /** Available Events */
            available_events: components["schemas"]["ActivityOption"][];
            /** Participations */
            participations?: components["schemas"]["ActivityOption"][];
            /** Availability Reasons */
            availability_reasons?: string[];
            /** Uncovered Critical Skills */
            uncovered_critical_skills?: string[];
        };
        /** EmployeeProfile */
        EmployeeProfile: {
            /** Employee Id */
            employee_id: string;
            /** Full Name */
            full_name: string;
            /** Department */
            department: string;
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Manager Id */
            manager_id: string | null;
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            /** Tenure Months */
            tenure_months: number;
            /**
             * Work Format
             * @enum {string}
             */
            work_format: "office" | "hybrid" | "remote";
            /**
             * Preferred Language
             * @enum {string}
             */
            preferred_language: "kk" | "ru" | "en";
            career_goal: components["schemas"]["CareerGoal"] | null;
            /** Skills */
            skills: {
                [key: string]: number;
            };
            /**
             * Last Review Date
             * Format: date
             */
            last_review_date: string;
        };
        /** EmployeeStatus */
        EmployeeStatus: {
            /** Employee Id */
            employee_id: string;
            /** Full Name */
            full_name: string;
            /** Department */
            department: string;
            /** Role */
            role: string;
            /** Grade */
            grade: string;
            /** Progress */
            progress: number;
            /** Status */
            status: string;
        };
        /** EventParticipation */
        EventParticipation: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Missed */
            missed: number;
            /** In Progress */
            in_progress: number;
            /** Overdue */
            overdue: number;
            /** Planned */
            planned: number;
            /** Cancelled */
            cancelled: number;
        };
        /** Evidence */
        Evidence: {
            /** Fact Id */
            fact_id: string;
            /**
             * Factor
             * @enum {string}
             */
            factor: "grade" | "skill_gap" | "history" | "target_requirements";
            /** Text */
            text: string;
        };
        /** GapCount */
        GapCount: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Employees */
            employees: number;
            /** Critical Employees */
            critical_employees: number;
        };
        /** Goal */
        Goal: {
            /** Role */
            role: string;
            /** Grade */
            grade: string;
            /** Inferred */
            inferred: boolean;
            /** Maintenance */
            maintenance: boolean;
            /**
             * Source
             * @default profile
             * @enum {string}
             */
            source: "profile" | "manual" | "automatic";
        };
        /** GoalInput */
        GoalInput: {
            career_goal: components["schemas"]["CareerGoal"] | null;
        };
        /** HROverview */
        HROverview: {
            /** As Of Date */
            as_of_date: string;
            /** Revision */
            revision: number;
            /** Total Employees */
            total_employees: number;
            /** Average Progress */
            average_progress: number;
            /** Total Participations */
            total_participations: number;
            /** Completion Rate */
            completion_rate: number;
            /** Skill Gaps */
            skill_gaps: components["schemas"]["GapCount"][];
            /** Employees Without Step */
            employees_without_step: components["schemas"]["EmployeeStatus"][];
            /** Participation */
            participation: components["schemas"]["EventParticipation"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryView */
        HistoryView: {
            /** Record Id */
            record_id: string;
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /** Date */
            date: string;
            /** Status */
            status: string;
            /** Completion Pct */
            completion_pct: number;
            /** Score */
            score: number | null;
            /** Feedback Rating */
            feedback_rating: number | null;
        };
        /** Identity */
        Identity: {
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "employee" | "hr";
            /** Employee Id */
            employee_id: string | null;
        };
        /** ImportResult */
        ImportResult: {
            /** Employees Created */
            employees_created: number;
            /** Employees Updated */
            employees_updated: number;
            /** History Created */
            history_created: number;
            /** History Updated */
            history_updated: number;
            /** Revision */
            revision: number;
            /** Employee Ids */
            employee_ids: string[];
            /** Message */
            message: string;
        };
        /** LoginInput */
        LoginInput: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ParticipationResult */
        ParticipationResult: {
            /** Record Id */
            record_id: string;
            /** Status */
            status: string;
            development: components["schemas"]["Development"];
        };
        /** RecommendationResult */
        RecommendationResult: {
            /** Run Id */
            run_id: string;
            /** Employee Id */
            employee_id: string;
            /** Revision */
            revision: number;
            /**
             * Context Version
             * @default
             */
            context_version: string;
            /**
             * Source
             * @enum {string}
             */
            source: "ai" | "fallback";
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Message */
            message: string;
            /** Steps */
            steps: components["schemas"]["RecommendedStep"][];
            /** Actions */
            actions: string[];
        };
        /** RecommendationState */
        RecommendationState: {
            /**
             * Status
             * @enum {string}
             */
            status: "not_generated" | "stale" | "ready" | "no_eligible_step";
            result: components["schemas"]["RecommendationResult"] | null;
        };
        /** RecommendedStep */
        RecommendedStep: {
            activity: components["schemas"]["ActivityOption"];
            /** Explanation */
            explanation: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** RoleOption */
        RoleOption: {
            /** Role */
            role: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "Junior" | "Middle" | "Senior" | "Lead";
            /** Required Skills */
            required_skills: {
                [key: string]: number;
            };
            /** Critical Skills */
            critical_skills: string[];
            /** Skill Names */
            skill_names: {
                [key: string]: string;
            };
        };
        /** SkillGain */
        SkillGain: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Before */
            before: number;
            /** After */
            after: number;
            /** Required */
            required: number;
        };
        /** SkillState */
        SkillState: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Current */
            current: number;
            /** Required */
            required: number;
            /** Gap */
            gap: number;
            /** Critical */
            critical: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    roles_api_v1_catalog_role_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOption"][];
                };
            };
        };
    };
    employees_api_v1_employees_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeProfile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    development_api_v1_employees__employee_id__development_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Development"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_employees__employee_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completion_api_v1_employees__employee_id__activities__event_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    goal_api_v1_employees__employee_id__career_goal_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Development"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_api_v1_employees__employee_id__activities__event_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_participation_api_v1_employees__employee_id__participations__record_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    last_recommendation_api_v1_employees__employee_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_recommendation_api_v1_employees__employee_id__recommendations_post: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hr_overview_api_v1_hr_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HROverview"];
                };
            };
        };
    };
    upload_api_v1_hr_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_hr_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_api_v1_hr_import_template_get: {
        parameters: {
            query?: {
                format?: "xlsx" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
