import { dateLabel, type RecommendationResult, type ActivityOption } from '@/shared/api/client';
import { Button, Empty, Loading, Notice, Tag } from '@/shared/ui';
import s from './recommendations.module.css';

const factorLabels: Record<string, string> = { grade: 'Ваш профиль', skill_gap: 'Изменение навыков', history: 'История участия', target_requirements: 'Связь с целью' };
export const formatLabels: Record<string, string> = { online: 'Онлайн', offline: 'Очно', self_paced: 'В своем темпе' };

export function Recommendations({ result, loading, readOnly, completing, onComplete }: { result: RecommendationResult | null; loading: boolean; readOnly: boolean; completing: string | null; onComplete: (activity: ActivityOption) => void }) {
  if (loading) return <Loading label="Подбираем шаги с учетом цели, навыков и истории…" />;
  if (!result) return <Empty>Получите персональные рекомендации — AI сопоставит доступные активности с вашей целью и историей.</Empty>;
  return <>{result.stale && <Notice kind="warning">Профиль изменился. Обновите подбор перед следующим действием.</Notice>}{result.source === 'fallback' && result.steps.length > 0 && <Notice kind="warning">{result.message}</Notice>}{!result.steps.length ? <Empty>{result.message}</Empty> : <><div className={s.source}>{result.source === 'ai' ? '✧ Выбор AI · факты проверены' : 'Резервный подбор'} · {(result.duration_ms / 1000).toFixed(1)} с{result.cached ? ' · из кеша' : ''}</div><div className={s.grid}>{result.steps.map((step, i) => <article className={s.card} key={step.activity.event_id}><div className={s.top}><span className={s.icon}>{['↗', '◇', '◎'][i]}</span><Tag>{i === 0 ? 'Следующий шаг' : 'Еще один вариант'}</Tag></div><h3>{step.activity.title}</h3><div className={s.meta}>{formatLabels[step.activity.format]} · {step.activity.duration_hours} ч{step.activity.next_session ? ` · ${dateLabel(step.activity.next_session)}` : ''}</div><div className={s.gain}>{step.activity.gains.map(g => <div key={g.skill_id}>{g.name} <strong>{g.before} → {g.after}</strong></div>)}</div><div className={s.reason}>{step.explanation}</div><details className={s.details}><summary>Почему этот шаг · {step.evidence.length} фактора</summary><div className={s.facts}>{step.evidence.map(f => <div className={s.fact} key={f.factor}><strong>{factorLabels[f.factor]}</strong>{f.text}</div>)}</div></details>{!readOnly && <Button variant="secondary" className={s.action} disabled={!!completing || result.stale || !step.activity.can_complete} onClick={() => onComplete(step.activity)}>{completing === step.activity.event_id ? 'Сохраняем…' : 'Отметить выполненным ✓'}</Button>}{!step.activity.can_complete && <div className={s.future}>Завершение станет доступно после проведения сессии.</div>}{readOnly && <div className={s.future}>Выполнение подтверждает сам сотрудник.</div>}</article>)}</div></>}<div className={s.trace}>{result.actions.map(action => <span key={action}>{action}</span>)}</div></>;
}
