'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { api, errorMessage, type Identity } from '@/shared/api/client';
import { Button, Notice } from '@/shared/ui';
import { useAuth } from './provider';
import s from './login.module.css';

export function Login() {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const { setUser } = useAuth(); const router = useRouter();
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const user = await api<Identity>('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }); setUser(user); router.replace(user.role === 'hr' ? '/hr' : '/me'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <div className={s.page}><section className={s.story}><div className={s.brand}>↗ career quest</div><h1>Развитие начинается<br />с понятного шага.</h1><p>Увидьте свои сильные стороны, выберите следующую цель и двигайтесь к ней с персональным AI-навигатором.</p><div className={s.route}>{['Ваша цель и навыки', 'Шаги, которые подходят именно вам', 'Прогресс, который видно'].map((text, i) => <div className={s.step} key={text}><span className={s.number}>{i + 1}</span>{text}</div>)}</div><div className={s.foot}>HACKALEM AI 2026 · CAREER QUEST</div></section><section className={s.formSide}><form className={s.form} onSubmit={submit}><span className={s.eyebrow}>ВАШЕ ПРОСТРАНСТВО РОСТА</span><h2>Добро пожаловать</h2><p className={s.subtitle}>Войдите, чтобы продолжить свой путь.</p>{error && <Notice kind="error">{error}</Notice>}<label className={s.field} htmlFor="username">Логин</label><input className={s.input} id="username" name="username" autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} required placeholder="Ваш логин" /><label className={s.field} htmlFor="password">Пароль</label><input className={s.input} id="password" name="password" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required placeholder="Введите пароль" /><Button className={s.submit} disabled={busy}>{busy ? 'Входим…' : 'Войти в пространство →'}</Button><div className={s.demo}>Демонстрация на синтетических данных.<br />Доступы по умолчанию: <code>employee / employee-demo-2026</code><br />и <code>hr / hr-demo-2026</code>. Настройки могут быть изменены.<div className={s.roleButtons}><button type="button" onClick={() => { setUsername('employee'); setPassword('employee-demo-2026'); }}>Заполнить: сотрудник</button><button type="button" onClick={() => { setUsername('hr'); setPassword('hr-demo-2026'); }}>Заполнить: HR</button></div></div></form></section></div>;
}
