"""Curated supplementary reading, verified 2026-09-23. Never generated by the LLM.

Original events and their gain rules are unchanged. Reading does not represent
completion of the catalog course. Missing mappings deliberately return no links.
"""


def resource(title, url, source, description):
    return dict(title=title, url=url, source=source, description=description, language='en')


ARCHITECTURE = resource('Основы архитектуры приложений', 'https://learn.microsoft.com/en-us/azure/architecture/guide/', 'Microsoft Learn', 'Сравните архитектурные подходы и подготовьте вопросы о своей системе.')
PERFORMANCE = resource('Производительность веб-приложений', 'https://web.dev/learn/performance', 'Google · web.dev', 'Разберите загрузку ресурсов и выберите, что измерить в своем приложении.')
STATISTICS = resource('Справочник по статистическим методам', 'https://www.itl.nist.gov/div898/handbook/', 'NIST / SEMATECH', 'Повторите проверку гипотез и планирование экспериментов.')
PRIORITIES = resource('Как расставить приоритеты', 'https://www.atlassian.com/team-playbook/plays/prioritize-tasks-how-to', 'Atlassian', 'Попробуйте оценить свои задачи по ценности и необходимым усилиям.')

EVENT_RESOURCES = {
    'EV_005': [ARCHITECTURE],
    'EV_006': [ARCHITECTURE],
    'EV_007': [ARCHITECTURE],
    'EV_008': [resource('Как писать понятную техническую документацию', 'https://developers.google.com/tech-writing', 'Google', 'Потренируйтесь делать предложения короче и подбирать структуру документа.')],
    'EV_009': [ARCHITECTURE],
    'EV_010': [resource('Практическое знакомство с Kubernetes', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/', 'Kubernetes', 'Пройдите примеры развертывания, масштабирования и обновления приложения.')],
    'EV_011': [resource('Распространенные уязвимости веб-приложений', 'https://owasp.org/projects/top-ten', 'OWASP', 'Ознакомьтесь с типами уязвимостей перед разбором примеров кода.')],
    'EV_012': [resource('Типы и обобщения в Python', 'https://docs.python.org/3/library/typing.html', 'Python Software Foundation', 'Попробуйте аннотации типов, обобщения и протоколы на своем коде.')],
    'EV_013': [resource('Руководство по системе типов TypeScript', 'https://www.typescriptlang.org/docs/handbook/intro.html', 'TypeScript', 'Разберите сужение типов и обобщения; повторите примеры в небольшом проекте.')],
    'EV_014': [PERFORMANCE],
    'EV_015': [PERFORMANCE],
    'EV_016': [resource('Как создавать доступные интерфейсы', 'https://web.dev/learn/accessibility/', 'Google · web.dev', 'Проверьте навигацию с клавиатуры, подписи элементов и структуру страницы.')],
    'EV_017': [resource('Управление состоянием в React', 'https://react.dev/learn/managing-state', 'React', 'Разберите, где хранить состояние и как передавать его между компонентами.')],
    'EV_018': [resource('Приемы написания надежных тестов', 'https://playwright.dev/docs/best-practices', 'Playwright', 'Попробуйте изоляцию тестов, устойчивые локаторы и проверки поведения.')],
    'EV_019': [resource('Первые нагрузочные тесты с k6', 'https://grafana.com/docs/k6/latest/get-started/', 'Grafana', 'Создайте небольшой нагрузочный сценарий и разберите его метрики.')],
    'EV_020': [STATISTICS],
    'EV_021': [STATISTICS],
    'EV_022': [resource('Оконные функции SQL', 'https://www.postgresql.org/docs/current/tutorial-window.html', 'PostgreSQL', 'Потренируйтесь считать показатели по группам строк без потери детализации.')],
    'EV_023': [resource('Как сделать дашборд понятным', 'https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips', 'Microsoft Learn', 'Выберите графики и расставьте акценты для аудитории своего отчета.')],
    'EV_024': [resource('Первые модели в scikit-learn', 'https://scikit-learn.org/stable/getting_started.html', 'scikit-learn', 'Повторите обучение модели, прогноз и оценку качества на примерах.')],
    'EV_025': [resource('Схема «звезда» для аналитики', 'https://learn.microsoft.com/en-us/power-bi/guidance/star-schema', 'Microsoft Learn', 'Разберите таблицы фактов и измерений, затем набросайте модель своих данных.')],
    'EV_026': [resource('Подготовка и проведение интервью с клиентом', 'https://www.atlassian.com/team-playbook/plays/customer-interview', 'Atlassian', 'Составьте вопросы, которые помогут понять опыт и задачи клиента.')],
    'EV_027': [PRIORITIES],
    'EV_031': [resource('Как подготовить учебное занятие', 'https://carpentries.github.io/instructor-training/', 'The Carpentries', 'Изучите приемы объяснения, практики и обратной связи для обучения взрослых.')],
    'EV_035': [resource('Последовательный поиск причин сбоя', 'https://sre.google/sre-book/effective-troubleshooting/', 'Google SRE', 'Потренируйтесь формулировать и проверять гипотезы о причинах ошибки.')],
    'EV_036': [resource('Советы по публичным выступлениям', 'https://www.toastmasters.org/resources/public-speaking-tips', 'Toastmasters International', 'Подготовьте короткое выступление и выберите навык для тренировки на встрече.')],
    'EV_037': [resource('Как помогать коллегам в роли наставника', 'https://www.atlassian.com/blog/leadership/how-to-be-a-good-mentor-for-your-whole-team', 'Atlassian', 'Подготовьте вопросы для первой встречи и подумайте, как давать полезную обратную связь.')],
    'EV_038': [resource('Роли и ответственность в команде', 'https://www.atlassian.com/team-playbook/plays/roles-and-responsibilities', 'Atlassian', 'Попробуйте описать зоны ответственности и обсудить ожидания с командой.')],
    'EV_039': [PRIORITIES],
    'EV_040': [resource('Как сформулировать проблему перед поиском решения', 'https://www.atlassian.com/team-playbook/plays/problem-framing', 'Atlassian', 'Разберите одну рабочую проблему: кого она затрагивает и какой результат нужен.')],
}
