import { test, expect, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('..');
const artifactDir = path.join(root, process.env.TEST_ARTIFACT_DIR || 'artifacts/round3');
fs.mkdirSync(artifactDir, { recursive: true });
function cli(args: string[]) { return execFileSync('docker', ['compose', 'exec', '-T', 'api', 'python', '-m', 'app.qa_acceptance', ...args], { cwd: root, encoding: 'utf8' }).trim(); }
async function login(page: Page, username: string, password: string) {
  await page.goto('/login');
  await page.getByLabel('Логин', { exact: true }).fill(username);
  await page.getByLabel('Пароль', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Войти в пространство' }).click();
  await expect(page).toHaveURL(username === 'hr' ? /\/hr$/ : /\/me$/);
}

test('full flow: HR import → employee goal → live AI → start → complete → HR', async ({ page }) => {
  const data = JSON.parse(cli(['prepare'])); const id = data.employee_id;
  data.bundle.employees[0].career_goal.target_grade = 'Middle';
  fs.writeFileSync(path.join(artifactDir, 'last-run.json'), JSON.stringify({ employee_id: id, password: data.password }));
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await login(page, 'hr', process.env.HR_PASSWORD || 'hr-demo-2026');
  const hrBefore = await (await page.request.get('/api/v1/hr/overview')).json();
  await page.getByRole('link', { name: 'Импорт данных' }).click();
  await page.getByLabel('Профили сотрудников: Excel или JSON').setInputFiles({ name: 'employees.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data.bundle)) });
  await page.getByLabel('История участия: Excel, JSON или CSV').setInputFiles({ name: 'history.csv', mimeType: 'text/csv', buffer: Buffer.from(data.history_csv) });
  await page.getByRole('button', { name: 'Проверить и импортировать' }).click();
  await expect(page.getByRole('heading', { name: 'Результат импорта' })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '01-import.png'), fullPage: true });
  const otherId = id.replace(/_FLOW$/, '_CRITICAL');
  const otherResponse = await page.request.post(`/api/v1/employees/${otherId}/recommendations?refresh=true`);
  expect(otherResponse.ok()).toBe(true);
  const other = await otherResponse.json(); expect(other.source).toBe('ai');
  cli(['account', '--employee-id', id]);
  await login(page, id, data.password);
  await expect(page.getByRole('heading', { name: 'Ваш следующий шаг, QA' })).toBeVisible();
  const initialDevelopment = await (await page.request.get(`/api/v1/employees/${id}/development`)).json();
  expect(initialDevelopment.goal.grade).toBe('Middle');
  await page.getByRole('button', { name: 'Изменить цель' }).click();
  await page.getByLabel('Целевая роль').selectOption('Backend Engineer');
  await page.getByLabel('Целевой грейд').selectOption('Senior');
  await expect(page.getByText('Требования выбранной цели', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '02-goal.png'), fullPage: true });
  const goalResponse = page.waitForResponse(r => r.url().endsWith('/career-goal') && r.request().method() === 'PATCH');
  await page.getByRole('button', { name: 'Сохранить цель', exact: true }).click();
  const savedGoalResponse = await goalResponse; expect(savedGoalResponse.status()).toBe(200);
  const savedGoal = await savedGoalResponse.json();
  expect(savedGoal.goal.grade).toBe('Senior'); expect(savedGoal.context_version).not.toBe(initialDevelopment.context_version);
  await expect(page.getByRole('button', { name: /Обновить подбор/ })).toBeEnabled({ timeout: 15000 });
  const aiResponse = page.waitForResponse(r => r.url().includes('/recommendations?refresh=true') && r.request().method() === 'POST');
  await page.getByRole('button', { name: /Обновить подбор/ }).click();
  const ai = await (await aiResponse).json();
  expect(ai.source).toBe('ai'); expect(ai.cached).toBe(false); expect(ai.duration_ms).toBeLessThan(10000);
  expect(ai.steps.length).toBeGreaterThan(0);
  expect(ai.steps.every((s: { evidence: { factor: string }[] }) => new Set(s.evidence.map(f => f.factor)).size >= 3)).toBe(true);
  await page.getByText('Почему этот шаг', { exact: false }).first().click();
  await page.screenshot({ path: path.join(artifactDir, '03-ai.png'), fullPage: true });
  const selected = ai.steps[0].activity;
  expect(selected.format).toBe('self_paced');
  const card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: selected.title, exact: true }) });
  await card.getByRole('button', { name: 'Начать →', exact: true }).click();
  const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible();
  const before = await page.getByRole('progressbar', { name: 'Соответствие карьерной цели', includeHidden: true }).getAttribute('aria-valuenow');
  const startResponse = page.waitForResponse(r => r.url().endsWith(`/${selected.event_id}/start`));
  await dialog.getByRole('button', { name: 'Начать активность', exact: true }).click();
  const started = await (await startResponse).json();
  expect(started.status).toBe('in_progress'); expect(String(started.development.progress)).toBe(before);
  await expect(dialog.getByText('В процессе', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '04-started.png') });
  const completionResponse = page.waitForResponse(r => r.url().endsWith(`/${selected.event_id}/complete`));
  await dialog.getByRole('button', { name: 'Отметить выполненным', exact: true }).click();
  const completed = await (await completionResponse).json();
  expect(completed.development.progress).toBeGreaterThan(completed.before_progress);
  await expect(page.getByText('Готово!', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: /Обновить подбор/ })).toBeEnabled({ timeout: 15000 });
  await expect(page.getByText(/Не удалось обновить подбор|Подбор не обновлен/)).toHaveCount(0);
  await page.screenshot({ path: path.join(artifactDir, '05-completed.png'), fullPage: true });
  await page.reload();
  await expect(page.getByRole('progressbar', { name: 'Соответствие карьерной цели' })).toHaveAttribute('aria-valuenow', String(completed.development.progress));
  await page.getByRole('button', { name: /История участия/ }).click();
  await expect(page.getByRole('row').filter({ hasText: selected.title }).filter({ hasText: 'Завершено' })).toHaveCount(1);
  await page.screenshot({ path: path.join(artifactDir, '06-history.png') });
  const fresh = await page.request.post(`/api/v1/employees/${id}/recommendations?refresh=true`);
  expect(fresh.ok()).toBe(true);
  const next = await fresh.json();
  expect(next.source).toBe('ai'); expect(next.context_version).not.toBe(ai.context_version);
  expect(next.steps.map((s: { activity: { event_id: string } }) => s.activity.event_id)).not.toContain(selected.event_id);
  await login(page, 'hr', process.env.HR_PASSWORD || 'hr-demo-2026');
  const otherAfter = await (await page.request.get(`/api/v1/employees/${otherId}/recommendations`)).json();
  expect(otherAfter.status).toBe('ready'); expect(otherAfter.result.run_id).toBe(other.run_id);
  const otherCached = await (await page.request.post(`/api/v1/employees/${otherId}/recommendations`)).json();
  expect(otherCached.cached).toBe(true); expect(otherCached.run_id).toBe(other.run_id);
  const hrAfter = await (await page.request.get('/api/v1/hr/overview')).json();
  for (const key of ['total_employees', 'total_participations', 'average_progress', 'completion_rate']) expect(hrAfter[key]).toBe(hrBefore[key]);
  await page.getByLabel('Поиск сотрудников').fill(id);
  await expect(page.getByRole('link', { name: 'Профиль ↗' })).toHaveCount(0);
  await page.getByLabel('Показать тестовые данные').check();
  await page.getByRole('link', { name: 'Профиль ↗' }).click();
  await expect(page.getByRole('button', { name: 'Изменить цель' })).toHaveCount(0);
  await expect(page.getByRole('progressbar', { name: 'Соответствие карьерной цели' })).toHaveAttribute('aria-valuenow', String(completed.development.progress));
  await page.screenshot({ path: path.join(artifactDir, '08-hr-profile.png'), fullPage: true });
  await page.getByRole('link', { name: 'Обзор команды' }).click();
  await expect(page.getByRole('columnheader', { name: 'ЗАПЛАНИРОВАНО', exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '09-hr-overview.png') });
  // Independently exercise dated participation on the synthetic preparation profile.
  const prepId = id.replace(/_FLOW$/, '_PREP');
  cli(['account', '--employee-id', prepId]);
  await login(page, prepId, data.password);
  await page.getByRole('button', { name: 'Подходящие активности', exact: true }).click();
  await page.getByRole('button', { name: 'Запланировать', exact: true }).first().click();
  const planning = page.getByRole('dialog');
  await planning.getByRole('button', { name: 'Запланировать участие', exact: true }).click();
  await expect(planning.getByRole('button', { name: 'Отметить выполненным', exact: true })).toBeDisabled();
  await page.screenshot({ path: path.join(artifactDir, '10-planned.png') });
  await planning.getByRole('button', { name: 'Отменить участие', exact: true }).click();
  await expect(page.getByText('Участие отменено.', { exact: false })).toBeVisible();
  fs.writeFileSync(path.join(artifactDir, 'flow-result.json'), JSON.stringify({ employee_id: id, ai_source: ai.source, ai_ms: ai.duration_ms, other_employee_remains_ready: otherAfter.status === 'ready', qa_does_not_change_hr_totals: true, selected_event: selected.event_id, next_events: next.steps.map((s: { activity: { event_id: string } }) => s.activity.event_id), before: completed.before_progress, after: completed.development.progress, record_id: completed.record_id, page_errors: errors }, null, 2));
  expect(errors).toEqual([]);
});

test('employee errors, responsive layout and goal editor', async ({ page }) => {
  await login(page, 'employee', process.env.EMPLOYEE_PASSWORD || 'employee-demo-2026');
  await page.getByRole('button', { name: 'Изменить цель' }).click();
  await page.getByLabel('Целевая роль').selectOption('Product Manager');
  await expect(page.getByText('Требования выбранной цели', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: /История участия/ }).click();
  await expect(page.getByText('На узком экране прокрутите таблицу вправо', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: path.join(artifactDir, '10-mobile.png'), fullPage: true });
});
