import { test, expect, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('..');
const artifactDir = path.join(root, 'artifacts/round2');
fs.mkdirSync(artifactDir, { recursive: true });
function cli(args: string[]) { return execFileSync('docker', ['compose', 'exec', '-T', 'api', 'python', '-m', 'app.qa_demo', ...args], { cwd: root, encoding: 'utf8' }).trim(); }
async function login(page: Page, username: string, password: string) {
  await page.goto('/login');
  await page.getByLabel('Логин', { exact: true }).fill(username);
  await page.getByLabel('Пароль', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Войти в пространство' }).click();
  await expect(page).toHaveURL(username === 'hr' ? /\/hr$/ : /\/me$/);
}

test('full flow: HR import → employee goal → live AI → start → complete → HR', async ({ page }) => {
  const data = JSON.parse(cli(['prepare'])); const id = data.employee_id;
  fs.writeFileSync(path.join(artifactDir, 'last-run.json'), JSON.stringify({ employee_id: id, password: data.password }));
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await login(page, 'hr', process.env.HR_PASSWORD || 'hr-demo-2026');
  await page.getByRole('link', { name: 'Импорт данных' }).click();
  await page.getByLabel('Профили сотрудников: Excel или JSON').setInputFiles({ name: 'employees.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data.bundle)) });
  await page.getByLabel('История участия: Excel, JSON или CSV').setInputFiles({ name: 'history.csv', mimeType: 'text/csv', buffer: Buffer.from(data.history_csv) });
  await page.getByRole('button', { name: 'Проверить и импортировать' }).click();
  await expect(page.getByRole('heading', { name: 'Результат импорта' })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '01-import.png'), fullPage: true });
  cli(['account', '--employee-id', id]);
  await login(page, id, data.password);
  await expect(page.getByRole('heading', { name: 'Ваш следующий шаг, QA' })).toBeVisible();
  await page.getByRole('button', { name: 'Изменить цель' }).click();
  await page.getByLabel('Целевая роль').selectOption('Backend Engineer');
  await page.getByLabel('Целевой грейд').selectOption('Senior');
  await expect(page.getByText('Требования выбранной цели', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '02-goal.png'), fullPage: true });
  const goalResponse = page.waitForResponse(r => r.url().endsWith('/career-goal') && r.request().method() === 'PATCH');
  await page.getByRole('button', { name: 'Сохранить цель', exact: true }).click();
  expect((await goalResponse).status()).toBe(200);
  await expect(page.getByRole('button', { name: /Обновить подбор/ })).toBeEnabled({ timeout: 15000 });
  const aiResponse = page.waitForResponse(r => r.url().includes('/recommendations?refresh=true') && r.request().method() === 'POST');
  await page.getByRole('button', { name: /Обновить подбор/ }).click();
  const ai = await (await aiResponse).json();
  expect(ai.source).toBe('ai'); expect(ai.cached).toBe(false); expect(ai.duration_ms).toBeLessThan(10000);
  expect(ai.steps.length).toBeGreaterThan(0);
  expect(ai.steps.every((s: { evidence: { factor: string }[] }) => new Set(s.evidence.map(f => f.factor)).size >= 3)).toBe(true);
  await page.getByText('Почему этот шаг', { exact: false }).first().click();
  await page.screenshot({ path: path.join(artifactDir, '03-ai.png'), fullPage: true });
  await page.getByRole('button', { name: 'Подходящие активности', exact: true }).click();
  const cloud = page.locator('div').filter({ has: page.getByRole('button', { name: 'Начать', exact: true }) }).filter({ hasText: 'Cloud Certification Prep' }).last();
  await cloud.getByRole('button', { name: 'Начать', exact: true }).click();
  const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible();
  const before = await page.getByRole('progressbar', { name: 'Соответствие карьерной цели', includeHidden: true }).getAttribute('aria-valuenow');
  const startResponse = page.waitForResponse(r => r.url().endsWith('/EV_009/start'));
  await dialog.getByRole('button', { name: 'Начать активность', exact: true }).click();
  const started = await (await startResponse).json();
  expect(started.status).toBe('in_progress'); expect(String(started.development.progress)).toBe(before);
  await expect(dialog.getByText('В процессе', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '04-started.png') });
  const completionResponse = page.waitForResponse(r => r.url().endsWith('/EV_009/complete'));
  await dialog.getByRole('button', { name: 'Отметить выполненным', exact: true }).click();
  const completed = await (await completionResponse).json();
  expect(completed.development.progress).toBeGreaterThan(completed.before_progress);
  await expect(page.getByText('Готово!', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: /Обновить подбор/ })).toBeEnabled({ timeout: 15000 });
  await expect(page.getByText(/Не удалось обновить подбор|Подбор не обновлен/)).toHaveCount(0);
  await page.screenshot({ path: path.join(artifactDir, '05-completed.png'), fullPage: true });
  await page.reload();
  await expect(page.getByRole('progressbar', { name: 'Соответствие карьерной цели' })).toHaveAttribute('aria-valuenow', String(completed.development.progress));
  await page.getByRole('button', { name: /История участия/ }).click();
  await expect(page.getByRole('row').filter({ hasText: 'Cloud Certification Prep' }).filter({ hasText: 'Завершено' })).toHaveCount(1);
  await page.screenshot({ path: path.join(artifactDir, '06-history.png') });
  // Future activity has a real local planning action; it cannot award skills early.
  await page.getByRole('button', { name: 'Подходящие активности', exact: true }).click();
  await page.getByRole('button', { name: 'Запланировать', exact: true }).first().click();
  await page.getByRole('dialog').getByRole('button', { name: 'Запланировать участие', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Отметить выполненным', exact: true })).toBeDisabled();
  await page.screenshot({ path: path.join(artifactDir, '07-planned.png') });
  await page.getByRole('dialog').getByRole('button', { name: 'Отменить участие', exact: true }).click();
  await expect(page.getByText('Участие отменено.', { exact: false })).toBeVisible();
  await login(page, 'hr', process.env.HR_PASSWORD || 'hr-demo-2026');
  await page.getByLabel('Поиск сотрудников').fill(id);
  await page.getByRole('link', { name: 'Профиль ↗' }).click();
  await expect(page.getByRole('button', { name: 'Изменить цель' })).toHaveCount(0);
  await expect(page.getByRole('progressbar', { name: 'Соответствие карьерной цели' })).toHaveAttribute('aria-valuenow', String(completed.development.progress));
  await page.screenshot({ path: path.join(artifactDir, '08-hr-profile.png'), fullPage: true });
  await page.getByRole('link', { name: 'Обзор команды' }).click();
  await expect(page.getByRole('columnheader', { name: 'ЗАПЛАНИРОВАНО', exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(artifactDir, '09-hr-overview.png') });
  fs.writeFileSync(path.join(artifactDir, 'flow-result.json'), JSON.stringify({ employee_id: id, ai_source: ai.source, ai_ms: ai.duration_ms, before: completed.before_progress, after: completed.development.progress, record_id: completed.record_id, page_errors: errors }, null, 2));
  expect(errors).toEqual([]);
});

test('employee errors, responsive layout and goal editor', async ({ page }) => {
  await login(page, 'employee', process.env.EMPLOYEE_PASSWORD || 'employee-demo-2026');
  await page.getByRole('button', { name: 'Изменить цель' }).click();
  await page.getByLabel('Целевая роль').selectOption('Product Manager');
  await expect(page.getByText('Требования выбранной цели', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: /История участия/ }).click();
  await expect(page.getByText('На узком экране прокрутите таблицу вправо', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: path.join(artifactDir, '10-mobile.png'), fullPage: true });
});
