'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { api, ApiError, errorMessage, type ImportResult } from '@/shared/api/client';
import { Button, Notice, Panel } from '@/shared/ui';
import s from './import.module.css';

export function ImportScreen() {
  const [employees, setEmployees] = useState<File | null>(null); const [history, setHistory] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [details, setDetails] = useState(''); const [result, setResult] = useState<ImportResult | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setDetails(''); setResult(null); const form = new FormData(); if (employees) form.append('employees', employees); if (history) form.append('history', history); try { setResult(await api<ImportResult>('/hr/import', { method: 'POST', body: form })); } catch (e) { setError(errorMessage(e)); if (e instanceof ApiError && e.details) setDetails(JSON.stringify(e.details, null, 2)); } finally { setBusy(false); } }
  return <div className={s.body}><header className={s.header}><h1>Новые данные — новые возможности</h1><p>Загрузите дополнительные профили и историю участия в исходном формате Career Quest.</p></header>{error && <Notice kind="error">{error}{details && <pre className={s.details}>{details}</pre>}</Notice>}<Panel><form onSubmit={submit}><div className={s.info}>Файлы проверяются вместе и применяются целиком. Если найдена ошибка, данные останутся без изменений. Повторная загрузка не создает дубликаты.</div><div className={s.files}><label className={s.file}><h3>Профили сотрудников</h3><p>JSON с полями meta и employees.<br />Срез: 1 октября 2026 года.</p><input type="file" name="employees" accept=".json,application/json" onChange={e => setEmployees(e.target.files?.[0] || null)} aria-label="JSON профилей сотрудников" /></label><label className={s.file}><h3>История участия</h3><p>CSV с исходными колонками.<br />Кодировка UTF-8.</p><input type="file" name="history" accept=".csv,text/csv" onChange={e => setHistory(e.target.files?.[0] || null)} aria-label="CSV истории участия" /></label></div><div className={s.actions}><Button disabled={busy || (!employees && !history)}>{busy ? 'Проверяем и загружаем…' : 'Проверить и импортировать ↥'}</Button><span className={s.hint}>До 4 МБ на файл</span></div></form></Panel>{result && <div className={s.result}><Notice>{result.message}</Notice><Panel><h2>Результат импорта</h2><div className={s.stats}>Новых профилей: {result.employees_created} · обновлено: {result.employees_updated}<br />Новых записей истории: {result.history_created} · обновлено: {result.history_updated}</div><div className={s.links}>{result.employee_ids.slice(0, 10).map(id => <Link key={id} href={`/hr/employees/${id}`}>Открыть профиль {id} и подобрать шаги ↗</Link>)}</div></Panel></div>}</div>;
}
